using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ZYM.Development.Models
{
    public enum MenuEnum
    {
        Navigation3D,
        BasicControls,
        PanningItems,
        BreatheLight,
        RingLoading,
        BallLoading,
        StreamerLoading,
        WaitLoading,
        CycleLoading,
        RollLoading,
        CutImage,
        CropAvatar,
        AnimationAudio,
        AMap,
        ThumbAngle,
        VerifyCode,
        CircularMenu,
        ChatEmoji,
        ProgressBar,
        Dashboard,
        PieControl,
        RoundMenu,
        Password,
        SongWords,
        TimeLine,
        Carousel,
        CarouselEx,
        Pagination,
        ScrollViewer,
        OtherControls,
        ScreenCut,
        TransitionPanel,
        SpotLight,
        DrawerMenu,
        RadarChart,
        BasicBarChart,
        ZooSemy,
        RulerControl,
        RainbowBtn,
        RoundPicker,
        LineChart,
        LogoAnimation,
        Thermometer,
        SnowCanvas,
        LoginWindow,
        Drawing,
        SpeedRockets,
        CountdownTimer,
        NumberCard,
        CropControl,
        Desktop,
        DrawPrize,
        EdgeLight,
        StarrySky,
        Shake,
        BubblleControl,
        CanvasHandWriting,
        Barrage,
        VirtualizingWrapPanel,
        AcrylicBlur,
        TaskbarInfo
    }
}
